"""initial schema

Revision ID: 65da4492d602
Revises: 
Create Date: 2026-09-03 09:11:56.206918
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '65da4492d602'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=80), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=7), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_events_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_usage_tenant_created', ['tenant_id', 'created_at'], unique=False)

    op.create_table('dify_bindings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=80), nullable=False),
    sa.Column('app_key', sa.String(length=200), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=True),
    sa.Column('metadata_value', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'purpose', name='uq_binding_tenant_purpose')
    )
    with op.batch_alter_table('dify_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dify_bindings_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=80), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('dify_document_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('batch', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'dify_document_id', name='uq_documents_dataset_doc')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_documents_tenant_created', ['tenant_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('quotas',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('monthly_token_limit', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('quotas')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_tenant_id'))
        batch_op.drop_index('ix_documents_tenant_created')
        batch_op.drop_index(batch_op.f('ix_documents_created_at'))

    op.drop_table('documents')
    with op.batch_alter_table('dify_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dify_bindings_tenant_id'))

    op.drop_table('dify_bindings')
    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.drop_index('ix_usage_tenant_created')
        batch_op.drop_index(batch_op.f('ix_usage_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_usage_events_created_at'))

    op.drop_table('usage_events')
    op.drop_table('tenants')
    # ### end Alembic commands ###
